# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160213_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dick',
            new_name='Post',
        ),
    ]
